#!/bin/bash

function addClient() {
	# Load params
	source /etc/wireguard/params
	echo ""
	echo "Tell me a name for the client."
	echo "Use one word only, no special characters."

	if [[ $SERVER_PUB_IP =~ .*:.* ]]; then
		echo "IPv6 Detected"
		ENDPOINT="[$SERVER_PUB_IP]:$SERVER_PORT"
	else
		echo "IPv4 Detected"
		ENDPOINT="$SERVER_PUB_IP:$SERVER_PORT"
	fi
	WG_CONFIG="/etc/wireguard/wg0.conf"
	LASTIP=$( grep "/32" $WG_CONFIG | tail -n1 | awk '{print $3}' | cut -d "/" -f 1 | cut -d "." -f 4 )
	if [[ "$LASTIP" = "" ]]; then
	CLIENT_ADDRESS="10.66.66.2"
	else
	CLIENT_ADDRESS="10.66.66.$((LASTIP+1))"
	fi
	CLIENT_WG_IPV6="fd42:42:42::2"

	# Adguard DNS by default
	CLIENT_DNS_1="176.103.130.130"

	CLIENT_DNS_2="176.103.130.131"
	IP=$(wget -qO- ifconfig.co);
	masaaktif=1
	exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
	CLIENT_NAME=trial`</dev/urandom tr -dc X-Z0-9 | head -c4`

	# Generate key pair for the client
	CLIENT_PRIV_KEY=$(wg genkey)
	CLIENT_PUB_KEY=$(echo "$CLIENT_PRIV_KEY" | wg pubkey)
	CLIENT_PRE_SHARED_KEY=$(wg genpsk)

	# Create client file and add the server as a peer
	echo "[Interface]
PrivateKey = $CLIENT_PRIV_KEY
Address = $CLIENT_ADDRESS/24,$CLIENT_WG_IPV6/64
DNS = $CLIENT_DNS_1,$CLIENT_DNS_2

[Peer]
PublicKey = $SERVER_PUB_KEY
PresharedKey = $CLIENT_PRE_SHARED_KEY
Endpoint = $ENDPOINT
AllowedIPs = 0.0.0.0/0,::/0" >>"$HOME/$SERVER_WG_NIC-client-$CLIENT_NAME.conf"

	# Add the client as a peer to the server
	echo -e "\n### Client $exp $CLIENT_NAME
[Peer]
PublicKey = $CLIENT_PUB_KEY
PresharedKey = $CLIENT_PRE_SHARED_KEY
AllowedIPs = $CLIENT_ADDRESS/32,$CLIENT_WG_IPV6/128" >>"/etc/wireguard/$SERVER_WG_NIC.conf"

	systemctl restart "wg-quick@$SERVER_WG_NIC"

	echo "It is also available in $HOME/$SERVER_WG_NIC-client-$CLIENT_NAME.conf"
	cp $HOME/$SERVER_WG_NIC-client-$CLIENT_NAME.conf /home/vps/public_html/$CLIENT_NAME.conf
	clear
	echo -e ""
	echo -e "==========-Trial-=========="
	echo -e "Wireguard	: http://$IP:81/$CLIENT_NAME.conf"
	echo -e "==========================="
	echo -e "Aktif Sampai    : $exp"
	rm -f /root/wg0-client-$CLIENT_NAME.conf
}
addClient